# -*- coding: utf-8 -*-
"""automate_SyuhadaAqlulHafiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZ92o8Ps0QobegaXzJilBHl9n1JfdfGR
"""

import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def run_preprocessing():
    print("🚀 Memulai proses otomatisasi preprocessing (Single Output)...")

    # 1. PATH INPUT
    input_folder = "JobDataset_raw"
    raw_file_name = "jobs_dataset.csv"  # <-- Sesuaikan dengan nama file mentahmu
    input_path = os.path.join(input_folder, raw_file_name)

    if not os.path.exists(input_path):
        raise FileNotFoundError(f"❌ File mentah tidak ditemukan di: {input_path}")

    df = pd.read_csv(input_path)

    # 2. CLEANING DATA
    df = df.dropna(subset=['salary'])
    job_cols = ['jobType/0', 'jobType/1', 'jobType/2', 'jobType/3']
    df[job_cols] = df[job_cols].fillna(False)
    df['externalApplyLink'] = df['externalApplyLink'].fillna('Unavailable')
    df = df.drop_duplicates(subset=['company', 'positionName', 'location', 'salary', 'description'])

    # 3. FEATURE ENGINEERING & BINNING
    df['salary_cleaned'] = df['salary'].astype(str).str.replace(r'[^\d.]', '', regex=True)
    df['salary_num'] = pd.to_numeric(df['salary_cleaned'], errors='coerce')

    df['desc_len'] = df['description'].astype(str).apply(len)
    df['posname_len'] = df['positionName'].astype(str).apply(len)

    bins_salary = [0, 70000, 120000, 200000, df['salary_num'].max()]
    labels_salary = ['Low', 'Medium', 'High', 'Very High']
    df['salary_bin'] = pd.cut(df['salary_num'], bins=bins_salary, labels=labels_salary)

    bins_rating = [0, 2, 3.5, 4.5, 5]
    labels_rating = ['Poor', 'Average', 'Good', 'Excellent']
    df['rating_bin'] = pd.cut(df['rating'], bins=bins_rating, labels=labels_rating)

    df = df[df['rating_bin'].isin(['Good', 'Excellent'])].copy()
    df = df.dropna(subset=['salary_bin'])

    # 4. MEMISAHKAN FITUR KATEGORI DAN NUMERIK (Tanpa Train-Test Split)
    cols_to_encode = [
        'company', 'location', 'positionName',
        'jobType/0', 'jobType/1', 'jobType/2', 'jobType/3',
        'searchInput/country', 'searchInput/position'
    ]
    cols_numeric = ['rating', 'desc_len', 'posname_len']

    # Gabungkan semua fitur ke dalam satu DataFrame X
    X = df[cols_numeric + cols_to_encode].copy()
    y = df['salary_bin']

    # 5. CATEGORICAL ENCODING
    X_encoded = pd.get_dummies(X, columns=cols_to_encode, drop_first=True)

    # 6. FEATURE SCALING
    scaler = StandardScaler()
    X_encoded[cols_numeric] = scaler.fit_transform(X_encoded[cols_numeric])

    # 7. GABUNGKAN KEMBALI FITUR DAN TARGET MENJADI SATU OUTPUT
    df_preprocessed = X_encoded.copy()
    df_preprocessed['salary_bin'] = y

    # 8. EKSPOR KE SATU FILE TUNGGAL
    output_folder = os.path.join("preprocessing")
    os.makedirs(output_folder, exist_ok=True)

    output_path = os.path.join(output_folder, "JobDataset_preprocessed.csv")
    df_preprocessed.to_csv(output_path, index=False)

    print(f"✅ Preprocessing Selesai! File tunggal berhasil disimpan di: {output_path}")

if __name__ == "__main__":
    run_preprocessing()