name: Automated Data Preprocessing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Diperbaiki dari python-node-version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    # 4. Menjalankan file otomasi python
    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_syuhadaaqlulhafiz.py

    # 5. Commit kembali file "JobDataset_preprocessed.csv" yang ada di folder preprocessing
    - name: Commit and Push Preprocessed Data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/JobDataset_preprocessed.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-updated preprocessed dataset via GitHub Actions" && git push)
