name: Automated Data Preprocessing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Mencegah workflow berjalan bersamaan dan bikin bentrok
jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    # 4. Menjalankan file otomasi python
    - name: Run Preprocessing Script
      run: |
        python ./preprocessing/automate_syuhadaaqlulhafiz.py

    # 5. Commit kembali file "JobDataset_preprocessed.csv"
    - name: Commit and Push Preprocessed Data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/JobDataset_preprocessed.csv
        git commit -m "chore: auto-generate preprocessed data" || echo "No changes to commit"
        git push
